ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS business_type VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS inquiry_type VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS contacted_salesperson VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS message TEXT;
